[master]
54.92.204.25  # IP do Control Plane

[workers]
13.221.126.46  # IP do Worker 1
13.221.254.1  # IP do Worker 2
3.88.235.43  # IP do Worker 3

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/caminho/para/sua/chave-vockey.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'